[package]
name = "phase1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
steganography = "1.0.2"
aes = "0.7.5"
block-modes = "0.8.1"
hex = "0.4"
# image = "*"
image = "=0.24.9" 
num = "*"
rand = "*"
sysinfo = "0.23"